### PR TITLE
Add COPYRIGHT file

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by leplatrem** [comment]
@smarnach This CI failure comes out of the blue. I can see that several Rust project do not commit their Cargo lock file. Is that a good practice? How can I make sure my builds are reproducibles, and that adding a COPYRIGHT would never fail?
Thanks for your insights ;)

**Comment by mostlygeek** [comment]
When we did this for application-services ([PR#1075](https://github.com/mozilla/application-services/pull/1075)) it was because there was code copied from ring into application-services and we had the wrong license header ([#1074](https://github.com/mozilla/application-services/issues/1074)).  This doesn't seem like the case with the remote-settings rust client.  

From our conversation today we're using the `ring` library because it's makes it easier to iterate on our code than `rc_crypto`.  Since we're not actually including source from `ring` into this repo, do we need to add this COPYRIGHT file?  When we ship the plan is to use `rc_crypto` and we will never ship any `ring`, compiled or otherwise. 

Does this sound right @leplatrem ?

**Comment by smarnach** [comment]
This kind of CI failure should be very rare.

The general rule is that [libraries should not commit `Cargo.lock`, while applications should](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries). Usually, this means that CI builds for libraries are not reproducible, while CI builds for applications are.

This design is intentional, and was chosen due to [tradeoffs](http://aturon.github.io/tech/2018/07/25/cargo-version-selection/). There's an [unstable feature to allow optionally using a different, reproducible version selection algorithm in Cargo](https://github.com/rust-lang/cargo/issues/5657), but I'm not sure what the current status is; I'm pretty sure it requires using Rust nightly, though. (In short, the current version selection algorithm always selects the newest semver-compatible version that satisfies all constraints, while trying to minimize the number of instances needed for each crate across the whole dependency graph. The alternative algorithm is to use the minimal version instead.)

I think our best option is to live with the random failures. Even if we did check in `Cargo.lock`, it would be ignored by crates depending on this library, and users of the lib might see failures even if the build is passing for us, which would be undesirable as well. The same would be true for using `--minimal-version`.

**Review by smarnach — APPROVED** [review]

**Comment by smarnach** [comment]
I reran the tests, and they are passing now, so apparently the crate that failed to compile has been fixed. In my experience something like this happens very rarely.

What's somewhat more frequent (but still rare) is that a crate is broken by a new Rust version. While Rust has strong backwards compatibility guarantees, there are a few exceptions, e.g. Rust is allow to add new impls that make type inference ambiguous, which can lead to compile errors for some crates. We could pin the Rust version in the Circle CI config to protect against that.

**Comment by smarnach** [comment]
(Incidentally there was a Rust release today, but Circle CI hasn't picked up the new version yet, so this wasn't the cause for the failure.)

**Comment by leplatrem** [comment]
>  Since we're not actually including source from ring into this repo, do we need to add this COPYRIGHT file? When we ship the plan is to use rc_crypto and we will never ship any ring, compiled or otherwise.
> 
> Does this sound right @leplatrem ?
> 

Yes, the main reasons to use `ring` in this repo are:
* have a pure-Rust implementation (no pulling and painful compiling of NSS, sqlite, sqlitecypher...)
* have a sort of standard implementation since ring is propular and wide-spread
* maximize our chances to find help (NSS is niche)

The COPYRIGHT file says «*Some code in the signature module (`src/client/signatures/`) leverages the `ring` crate*». Even if once integrated application-services consumers, only the rc_crypto part will be compiled, we can keep this part.

> The general rule is that libraries should not commit Cargo.lock, while applications should. Usually, this means that CI builds for libraries are not reproducible, while CI builds for applications are.

Thanks for your detailed explanation Sven! Really appreciate it!
That part makes total sense. The dependabot pull-requests will help us keep track of that.

>While Rust has strong backwards compatibility guarantees, there are a few exceptions, e.g. Rust is allowed to add new impls that make type inference ambiguous, which can lead to compile errors for some crates. We could pin the Rust version in the Circle CI config to protect against that.

I think I would want to always run the tests on the latest version of Rust. We should be fine :)

**Pull request merged**
